name: Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Run tests
      run: make test
      
    - name: Build for current platform
      run: make build
      
    - name: Test basic functionality
      run: |
        echo "Testing basic functionality..."
        echo -e "line1\nline2\nline3\nline4\nline5" > test.txt
        ./fastreader test.txt gen
        ./fastreader test.txt cnt
        ./fastreader test.txt 1
        ./fastreader test.txt 1:3
        ./fastreader test.txt -1
        rm -f test.txt test.txt.frc
        echo "All tests passed!"

  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd]
        goarch: [amd64, 386, arm64, arm]
        exclude:
          # Exclude unsupported combinations
          - goos: darwin
            goarch: 386
          - goos: darwin
            goarch: arm
          - goos: freebsd
            goarch: 386
          - goos: freebsd
            goarch: arm64
          - goos: freebsd
            goarch: arm
          - goos: windows
            goarch: arm64
          - goos: windows
            goarch: arm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
      run: make ${{ matrix.goos }}-${{ matrix.goarch }}
      
    - name: Verify binary exists
      run: |
        if [ "${{ matrix.goos }}" = "windows" ]; then
          ls -la dist/fastreader-${{ matrix.goos }}-${{ matrix.goarch }}.exe
        else
          ls -la dist/fastreader-${{ matrix.goos }}-${{ matrix.goarch }}
        fi
